### PR TITLE
Add subfolders for 3.6 and 3.8, add xmlsec for 3.8

### PR DESCRIPTION
**Pull request by hjwp**
In procurement, we're building our own version of xmlsec because of a bug.  we're working from 3.8.

this pull request proposes adding a new folder hierarchy so that we can have packages for different versions of alpine.

it includes a first package for 3.8 for xmlsec based on what we're doing merged with the 3.6 xmlsec that we're compiling.  I have made some "educated" guesses about what that `APKBUILD` script is and how it works but I don't really know what I'm doing.

presumably if this is merged, some sort of script that runs on jenkins somewhere will need to be udpated to build and push multiple versions' images...

cc @bobthemighty

### CODE REVIEW

**Comment by egidijus** [comment]
Cool, I need to test this and if this works, we can try and publish this.

**Comment by hjwp** [comment]
the bob suggested we / someone should pair on this before merging it

**Comment by egidijus** [comment]
Let's do that.

**Comment by hjwp** [comment]
this may still be a good idea, but as far as I'm concerned the urgency is gone bc we can use the https://github.com/madedotcom/alpine-python instead, can close if y'all want.

**Pull request closed without merging**
